// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
